swagger: '2.0'

info:
  title: ArgentBank API documentation
  description: Contains all available API endpoints in this codebase (fixed), _and_ __suggests a way to implement transactions endpoints__
  termsOfService: http://swagger.io/terms/
  version: '1.1.0'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
tags: 
- name: 'User Module'
  description: 'User operations'
- name: 'Transactions Module'
  description: 'Transactions operations'

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API to Login
      parameters:
        - in: body
          name: Body
          description: Login credentials
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Login successful
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid fields
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API to Signup
      parameters:
        - in: body
          name: Body
          description: Signup data
          required: true
          schema:
            $ref: '#/definitions/SignupRequest'
      produces:
        - application/json
      responses:
        '201':
          description: Signup successful
          schema:
            $ref: '#/definitions/SignupResponse'
        '400':
          description: Invalid fields
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'

  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Fetch profile
      description: API to fetch a user profile
      parameters:
        - in: header
          name: Authorization
          description: Bearer + jwt
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ProfileResponse'
        '400':
          description: Invalid fields
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'

    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update profile
      description: API to update a user's first and last name
      parameters:
        - in: header
          name: Authorization
          description: Bearer + jwt
          required: true
        - in: body
          name: Body
          description: User profile attributes to update
          required: true
          schema:
            $ref: '#/definitions/ProfileEditRequest'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ProfileResponse'
        '400':
          description: Invalid fields
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'

  /transactions/account/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Fetch account transactions
      description: API to fetch a user's account transactions for the current month
      parameters:
        - in: header
          name: Authorization
          description: Bearer + jwt
          required: true
        - in: path
          name: accountId
          description: account ID
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsCollectionResponse'
        '400':
          description: Invalid fields
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '422':
          description: Account ID not found
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
          
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Create account transaction
      description: API to add a transaction to an user's account
      parameters:
        - in: header
          name: Authorization
          description: Bearer + jwt
          required: true
        - in: path
          name: accountId
          description: account ID
          type: string
          required: true
        - in: body
          name: Body
          description: Transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionsRequest'
      produces:
        - application/json
      responses:
        '201':
          description: User transaction created successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid fields
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '422':
          description: Account ID not found
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'

  /transactions/transaction/{transactionsId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Fetch a transaction
      description: API to fetch a specific user transaction
      parameters:
        - in: header
          name: Authorization
          description: Bearer + jwt
          required: true
        - in: path
          name: transactionsId
          description: transaction ID to fetch
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid fields
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '422':
          description: Transaction ID not found
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
          
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Add content to a transaction
      description: API to add a category and/or notes to a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Bearer + jwt
          required: true
        - in: path
          name: transactionsId
          description: transaction ID to fetch
          required: true
          type: string
        - in: body
          name: Body
          description: Transaction attributes to update
          required: true
          schema:
            $ref: '#/definitions/TransactionsEditRequest'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction updated successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid fields
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '422':
          description: Transaction ID not found
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
    
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Edit content of a transaction
      description: API to edit the category and/or notes of a user transaction
      parameters:
        - in: header
          name: Authorization
          description: Bearer + jwt
          required: true
        - in: path
          name: transactionsId
          description: transaction ID to fetch
          required: true
          type: string
        - in: body
          name: Body
          description: Transaction attributes to update
          required: true
          schema:
            $ref: '#/definitions/TransactionsEditRequest'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction updated successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid fields
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '422':
          description: Transaction ID not found
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
          
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete a transaction or its editable content
      description: API to delete a transaction's category and/or notes, or the transaction itself
      parameters:
        - in: header
          name: Authorization
          description: Bearer + jwt
          required: true
        - in: path
          name: transactionsId
          description: transaction ID to fetch
          required: true
          type: string
        - in: query
          name: deleteTransaction
          description: whether the transaction should be deleted
          required: false
          type: boolean
        - in: query
          name: deleteCategory
          description: whether the transaction's category should be deleted
          required: false
          type: boolean
        - in: query
          name: deleteNotes
          description: whether the transactions's notes should be deleted
          required: false
          type: boolean
      produces:
        - application/json
      responses:
        '200':
          description: User transaction deleted successfully
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '400':
          description: Invalid fields __or absence of a query param__
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '401':
          description: User not authenticated
        '403':
          description: User not authorized
        '422':
          description: Transaction ID not found
          schema:
            $ref: '#/definitions/MessageOnlyResponse'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/MessageOnlyResponse'

securityDefinitions:
  Bearer:
    name: Authorization
    in: header
    description: \"Bearer\" + jwt (separated by a space)
    type: apiKey

definitions:
  LoginRequest:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  LoginResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          token:
            type: string

  SignupRequest:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  SignupResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          password:
            type: string
          firstName:
            type: string
          lastName:
            type: string
          createdAt:
            type: string
          updatedAt:
            type: string

  ProfileEditRequest:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  ProfileResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          firstName:
            type: string
          lastName:
            type: string
          createdAt:
            type: string
          updatedAt:
            type: string

  TransactionsRequest:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      type:
        type: string
  TransactionsEditRequest:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          accountId:
            type: string
          date:              
            type: string
          decription:
            type: string
          amount:
            type: number
          balance:
            type: number
          type:
            type: string
          category:
            type: string
          notes:
            type: string
          createdAt:
            type: string
          updatedAt:
            type: string
  TransactionsCollectionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            accountId:
              type: string
            date:
              type: string
            description:
              type: string
            amount:
              type: number
            balance:
              type: number
            type:
              type: string
            category:
              type: string
            notes:
              type: string
            createdAt:
              type: string
            updatedAt:
              type: string
        
  MessageOnlyResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
